#version: '3'
networks:
  mynet:
    ipam:
      config:
        - subnet: 172.20.0.0/16
volumes:
  portainer_data:
    #相当于执行 docker volume create portainer_data
    #生成的目录 /var/lib/docker/volumes/portainer_data/_data/
    #注意：此设置当容器停止或删除，_data 目录会变为空
    name: portainer_data #生成的卷名(不指定则卷名自行生成)
    driver: local

services:
    portainer:
        image: portainer/portainer-ce:latest
        hostname: portainerHost
        # 映射端口 【宿主机端口:容器端口】
        ports:
            #- "8000:8000"
            - "9443:9443"
        # 目录挂载 【宿主机目录:容器目录】
        volumes:
            # 注意：宿主机目录不用事先存在，没有会自动生成目录，但是如果目录没有内容，则容器目录也会被清空。
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        # 容器名称
        container_name: portainer
        restart: always
        # 相当于 docker run -i
        stdin_open: true
        # 相当于 docker run -t
        tty: true
        #networks:
        #    mynet:
                 #为容器指定内网ip
        #        ipv4_address: 172.20.0.10
        # 容器的ip在设置的网络名的网段中随机生成
        #networks:
        #    - mynet