#version: '2'
services:
    mysql-dc:
        # 依赖于mysql（8.0.26 MySQL Community Server - GPL）镜像
        image: mysql:8.0.26
        hostname: mysqlHost
        #解决外部无法访问
        command: --default-authentication-plugin=mysql_native_password
        # 映射端口 【宿主机端口:容器端口】
        ports:
            - "3306:3306"
        # 目录挂载 【宿主机目录:容器目录】
        volumes:
            - /usr/local/docker/mysql/data:/var/lib/mysql
            - /usr/local/docker/mysql/conf:/etc/mysql/conf.d
            # 数据库还原目录 可将需要还原的sql文件放在这里
            - /usr/local/docker/mysql/source:/docker-entrypoint-initdb.d
        #以下配置初始值，解决无法访问的问题
        environment:
            #方式1：
            #- "MYSQL_ROOT_PASSWORD=123456"
            #- "MYSQL_DATABASE=mydb123"
            #- "TZ=Asia/Shanghai"
            #- "MYSQL_USER=ljs"
            #- "MYSQL_PASSWORD=ljsljs"
            #方式2：
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: mydb123
            TZ: Asia/Shanghai
            MYSQL_USER: ljs
            MYSQL_PASSWORD: ljsljs
        # 容器名称
        container_name: mysql-test
        restart: always
        # 相当于 docker run -i
        stdin_open: true
        # 相当于 docker run -t
        tty: true
        # 解决服务启动顺序问题（依赖），先启动php7.3-dc和php7.4-dc两个服务，最后才启动mysql-dc服务
        #depends_on:
        #    - php7.3-dc
        #    - php7.4-dc