#version: "3"

services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing-s
    hostname: my-s
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /wherever/st-sync:/var/syncthing #默认生成存放配置的文件夹config和同步目录Sync
      - /www1/web:/var/syncthing/web_s   #nginx静态服务器和php动态服务器上的网页目录
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
