#version: "3"

volumes:
  syncFolder:
    #相当于执行 docker volume create sync_folder
    #生成的目录 /var/lib/docker/volumes/sync_folder/_data/
    #注意：此设置当容器停止或删除，_data 目录会变为空
    name: sync_folder #临时目录
    driver: local
    driver_opts:
      o: bind
      type: none
      #注意：此设置需要宿主机目录要事先存在（此目录不会因为容器的停止与删除而被清空）
      device: /www1/web #此目录存放网页文件

services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: ${HOSTNAME:-syncthingHost} # 无HOSTNAME变量时用"syncthingHost"
    environment:
      - PUID=1000
      - PGID=1000
      - STGUIADDRESS=
    volumes:
      - /wherever/st-sync:/var/syncthing #默认生成存放配置的文件夹config和同步目录Sync
      - syncFolder:/syncthing            #syncthing容器上新建的目录
    ports:
      #- 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
